<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'All Time' => 'Koko aika',
  'Past Week' => 'Kuluva viikko',
  'Publish Day' => 'Julkaisupäivä',
  'Publish Week' => 'Julkaisuviikko',
  'Time Period' => 'Aika',
  'Today' => 'Tänään',
  'Articles of organization' => 'Uutiset kustannuspaikalla ',
  'Articles of user' => 'Uutiset käyttäjätunnuksella',
  'Brand' => 'Sivusto',
  'Choose One' => 'Valitse yksi',
  'Comparison' => 'Vertailu',
  'Data is updated every 15 minutes.' => 'Luvut päivittyvät noin 15 minuutin välein.',
  'Escenic username' => 'Escenic käyttäjätunnus',
  'External Link' => 'Ulkoinen linkki',
  'Facebook Comments' => 'Facebook kommentit',
  'Facebook Likes' => 'Facebook tykkäykset',
  'Facebook Shares' => 'Facebook jaot',
  'Facebook Total' => 'Facebook yhteensä',
  'Facebook shares, LinkedIn shares and tweets' => 'Facebook jaot, LinkedIn jaot ja tweetit',
  'Find Articles' => 'Hae artikkelit',
  'Find Results' => 'Hae tulokset',
  'Internal Link' => 'Sisäinen linki',
  'LinkedIn Shares' => 'LinkedIn jaot',
  'Organization ID' => 'Kustannuspaikkakoodi',
  'Page Views' => 'Sivulataukset',
  'Previously used addresses' => 'Aiemmin käytetyt osoitteet',
  'Published' => 'Julkaistu',
  'Search' => 'Haku',
  'Search Engine' => 'Hakukone',
  'Search terms used to find this page from search engines.' => 'Hakulauseet joilla sivu on löydetty hakukoneesta,',
  'Shares Per Hour' => 'Jakoja tunnissa',
  'Shares Total' => 'Jaot yhteensä',
  'Social Media Comparison' => 'Some Vertailu',
  'The number of Facebook comments given on the shares and likes linking to this page.' => 'Facebook kommenttien määrä tykkäyksissä ja jaoissa jotka linkittävät tähän sivuun.',
  'The number of Facebook likes given on the shares linking to this page.' => 'Facebook tykkäysten määrä jaoissa jotka linkittävät tähän artikkeliin.',
  'The number of Facebook shares, LinkedIn shares and tweets in an hour.' => 'Facebook jakojen, LinkedIn jakojen ja tweettien määrä tunnissa.',
  'The total of Facebook shares, comments and likes' => 'Facebook jaot, kommentit ja tykkäykset yhteensä',
  'This metric does not match with the numbers of like button. Like button includes comments and likes.' => 'Tämä luku ei vastaa suosittelupainikkeessa olevaa lukua, koska suosittelupainikkeen luvuissa on mukana myös kommentit ja tykkäykset.',
  'Title' => 'Otsikko',
  'Total Shares' => 'Jaot yhteensä',
  'Traffic Sources' => 'Liikenteen lähteet',
  'Tweets' => 'Tweetit',
  'Web Address' => 'Mikä tahansa verkko-osoite',
  'Websites that link directly to the page.' => 'Verkkosivut jotka linkittävät tähän sivuun.',
  'You can send feedback about the service to: ' => 'Voit lähettää palautetta palvelusta osoitteeseen: ',
);
