<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Apr' => 'Huhti',
  'April' => 'Huhtikuu',
  'Aug' => 'Elo',
  'August' => 'Elokuu',
  'Dec' => 'Joulu',
  'December' => 'Joulukuu',
  'Feb' => 'Helmi',
  'February' => 'Helmikuu',
  'Friday' => 'Perjantai',
  'Jan' => 'Tammi',
  'January' => 'Tammikuu',
  'Jul' => 'Heinä',
  'July' => 'Heinäkuu',
  'Jun' => 'Kesä',
  'June' => 'Kesäkuu',
  'Mar' => 'Maalis',
  'March' => 'Maaliskuu',
  'May' => 'Toukokuu',
  'Monday' => 'Maanantai',
  'Nov' => 'Marras',
  'November' => 'Marraskuu',
  'Oct' => 'Loka',
  'October' => 'Lokakuu',
  'Saturday' => 'Lauantai',
  'Sep' => 'Syys',
  'September' => 'Syyskuu',
  'Sunday' => 'Sunnutai',
  'Thursday' => 'Torstai',
  'Tuesday' => 'Tiistai',
  'Wednesday' => 'Keskiviikko',
);
